services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - fast_api_template

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - fast_api_template

volumes:
  db_data:

networks:
  fast_api_template:
    name: "fast_api_template"
    driver: "bridge"
